# Generated by Django 5.2.4 on 2025-08-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstage',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='orderstage',
            name='update_history',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='remark',
        ),
        migrations.AddField(
            model_name='orderstage',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='note',
            field=models.TextField(blank=True, help_text='Any additional notes about the vendor.'),
        ),
    ]
