# Generated by Django 5.2.4 on 2025-08-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0002_remove_orderstage_remark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstage',
            old_name='note',
            new_name='remark',
        ),
    ]
