# Generated by Django 5.2.4 on 2025-08-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0003_rename_note_orderstage_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstage',
            name='note',
            field=models.TextField(blank=True, help_text='Any additional notes for this stage.'),
        ),
    ]
