# Generated by Django 5.2.4 on 2025-08-07 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0004_alter_measurement_measurement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_tracker.pipelinestage'),
        ),
        migrations.DeleteModel(
            name='VendorRole',
        ),
    ]
