# Generated by Django 5.2.4 on 2025-08-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0005_alter_vendor_role_delete_vendorrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstage',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='New', max_length=20),
        ),
    ]
