# Generated by Django 5.2.4 on 2025-08-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0005_customer_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Particulars',
        ),
    ]
