# Generated by Django 5.2.4 on 2025-08-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0006_alter_order_status_alter_orderstage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Aborted', 'Aborted')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstage',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Aborted', 'Aborted')], default='New', max_length=20),
        ),
    ]
