# Generated by Django 5.2.4 on 2025-08-16 16:17

import django.db.models.deletion
from django.db import migrations, models

def populate_vendor_roles(apps, schema_editor):
    Vendor = apps.get_model('production_tracker', 'Vendor')
    VendorRole = apps.get_model('production_tracker', 'VendorRole')
    for role_name in Vendor.objects.values_list('role__name', flat=True).distinct():
        if role_name:
            VendorRole.objects.get_or_create(name=role_name)

class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0007_remove_invoice_paid_invoice_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRole',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(populate_vendor_roles),
        migrations.AddField(
            model_name='pipelinestage',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_tracker.vendorrole'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_tracker.vendorrole'),
        ),
    ]
