# Generated by Django 5.2.4 on 2025-08-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0007_alter_order_status_alter_orderstage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_tracker.measurement'),
        ),
    ]
