# Generated by Django 5.2.4 on 2025-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0008_vendorrole_pipelinestage_role_alter_vendor_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='note',
        ),
        migrations.AddField(
            model_name='vendor',
            name='remark',
            field=models.TextField(blank=True, help_text='Any additional remarks about the vendor.'),
        ),
    ]
