# Generated by Django 5.2.4 on 2025-08-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0009_remove_vendor_note_vendor_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstage',
            name='remark',
        ),
    ]
