# Generated by Django 5.2.4 on 2025-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0009_alter_measurement_measurement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
