# Generated by Django 5.2.4 on 2025-08-16 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0010_remove_orderstage_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_tracker.pipelinestage'),
        ),
    ]
