# Generated by Django 5.2.4 on 2025-08-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracker', '0011_remove_measurement_value_measurement_ankle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='specifications',
            field=models.TextField(blank=True),
        ),
    ]
