# .github/workflows/main.yml

name: Build and Deploy to Render

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/Clothing-Tracker:latest

      - name: Trigger Render Deploy
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
